const emojis = Object.freeze({
  alnMnstr: '👾',
  bmb: '💣',
  brfcs: '💼',
  cllsn: '💥',
  crsMrk: '❌',
  ctlKnbs: '🎛️',
  crwn: '👑',
  dggr: '🗡️',
  dsktpCmptr: '🖥️',
  elctrcPlg: '🔌',
  exclmtnMrk: '❗',
  fctry: '🏭',
  fr: '🔥',
  glngStr: '🌟',
  gmStn: '💎',
  heavyPlsSgn: '➕',
  hndrdPts: '💯',
  hrtSt: '♥️',
  idBtn: '🆔',
  infrmtn: 'ℹ️',
  kycpNmbrSgn: '#️⃣',
  ldSpkr: '📢',
  lptpCmptr: '💻',
  mgPhn: '📣',
  ntry: '⛔',
  nwBtn: '🆕',
  plBtn: '▶️',
  pntngRght: '👉',
  prhbtd: '🚫',
  pstl: '🔫',
  qstnMrk: '❓',
  rckt: '🚀',
  rdHrt: '❤️',
  rptBtn: '🔁',
  rvlvngHrts: '💞',
  skll: '💀',
  smlHrtEys: '😍',
  sngGlss: '🕶️',
  spchBlln: '💬',
  sprkls: '✨',
  sprtsMedl: '🏅',
  ssBtn: '🆘',
  stpSgn: '🛑',
  str: '⭐',
  thrd: '🧵',
  tpHt: '🎩',
  trph: '🏆',
  twHrts: '💕',
  vsBtn: '🆚',
  wrnng: '⚠️',
  whteHvyChckMrk: '✅',
  zzz: '💤'
});

module.exports = emojis;
